export const ADD_TASK = 'ADD_TASK';
export const REMOVE_ALL_TASKS = 'REMOVE_ALL_TASKS';
export const REMOVE_TASK = 'REMOVE_TASK';
export const CHANGE_TASK = 'CHANGE_TASK';
export const FILTER_ALL = 'FILTER_ALL';
export const FILTER_IS_COMPLETED = 'FILTER_IS_COMPLETED';
export const FILTER_IS_NOT_COMPLETED = 'FILTER_IS_NOT_COMPLETED';
